In [ ]:
lst=range(1, 20)
f=[items for items in x if items%3==0 or items%4==0 ]
f

In [ ]:
out1=[x*3 if x%2==0 else x*5 for x in lst]

In [ ]:
out1=[]

In [ ]:
def ex3(data):
    with open(data) as f: 
        readline=f.read().split("\n")
    input_data=[]
    for lines in range(0,len(readline),2):
        # print(lines)
        input_data.append(readline[lines])
    input_data
    lambda_function = lambda row: sum(list(map(int, row.split(",")[1:]))) / 5
    out = min(input_data, key=lambda_function)
    return (lambda_function, out)
ex3('ex3_data.txt')
    # new_list = min(lines, key=l_func)
    # return (l_func, new_list)
# s=[student1,33,34,35,36,45]

In [ ]:
with open('ex3_data.txt') as f: 
    readline=f.read().split("\n")
input_data=[]
for lines in range(0,len(readline),2):
    input_data.append(readline[lines])
input_data

In [ ]:
a=(lambda x: x*2)
a(8)

In [ ]:
lines = [{
            "name": "student19",
            "test1": "70",
            "test2": "70",
            "test3": "83",
            "test4": "99",
            "test5": "97"
        },
            {
            "name": "student20",
            "test1": "68",
            "test2": "68",
            "test3": "81",
            "test4": "74",
            "test5": "76"
        },
            {
            "name": "student21",
            "test1": "74",
            "test2": "73",
            "test3": "84",
            "test4": "84",
            "test5": "69"
        },
            {
            "name": "student22",
            "test1": "65",
            "test2": "87",
            "test3": "85",
            "test4": "78",
            "test5": "98"
        },
            {
            "name": "student23",
            "test1": "88",
            "test2": "95",
            "test3": "85",
            "test4": "67",
            "test5": "93"
        },
            {
            "name": "student24",
            "test1": "80",
            "test2": "91",
            "test3": "86",
            "test4": "99",
            "test5": "96"
        },
            {
            "name": "student25",
            "test1": "77",
            "test2": "86",
            "test3": "79",
            "test4": "70",
            "test5": "92"
        },
            {
            "name": "student26",
            "test1": "80",
            "test2": "78",
            "test3": "75",
            "test4": "69",
            "test5": "87"
        }, ]

In [ ]:

import json
# with open(filename) as infile:
#     grades = json.load(infile)
    
# BEGIN SOLUTION
print(sorted(lines, key=lambda lines: lines['test3']))

In [ ]:
students = ['john', 'jane', 'doe']
# make upper case


# method 1 create new list and loop
# new_list = []
# for student in students:
#     new_list.append(student.title())

# print(new_list)

# method 2 -- use list comprehension

# print([student[0].upper()+student[1:] for student in students])

# method 3 -- use lambda

print(list(map(lambda student: student.title(), students)))

In [ ]:
students = [
    {'username': 'john', 'grade': 50},
    {'username': 'jane', 'grade': 80},
    {'username': 'doe', 'grade': 35},
    {'grade': 89, 'username': 'Kelly'}
]

from pprint import pprint
# return sorted(students, key=lambda studen: studen['grade'])
# print()
# print(sorted(students, key=lambda student: student['username'], reverse=True))

In [ ]:
input_dict = {
    'January': 31,
    'February': 28,
    'March': 31,
    'April': 30,
    'May': 31,
    'June': 30,
    'July': 31,
    'August': 31,
    'September': 30,
    'October': 31,
    'November': 30,
    'December': 31,
}

In [ ]:

def ex6(input_dict, test_value):
    out=[]
    for key, value in input_dict.items():
        if value==test_value:
            out.append(key)
    return out
ex6(input_dict,31)

In [ ]:
bb=['student1: B',
                          'student2: B',
                          'student3: B',
                          'student4: B',
                          'student5: B',
                          'student6: B',
                          'student7: C',
                          'student8: C',
                          'student9: B',
                          'student10: C',
                          'student11: C',
                          'student12: C',
                          'student13: B',
                          'student14: B',
                          'student15: C',
                          'student16: B',
                          'student17: B',
                          'student18: B',
                          'student19: C',
                          'student20: B',
                          'student21: B',
                          'student22: C',
                          'student23: B',
                          'student24: B',
                          'student25: A',
                          'student26: B',
                          'student27: C',
                          'student28: B',
                          'student29: B',
                          'student30: B',
                          'student31: B',
                          'student32: C',
                          'student33: B',
                          'student34: B',
                          'student35: B',
                          'student36: C',
                          'student37: B',
                          'student38: B',
                          'student39: C',
                          'student40: C',
                          'student41: B',
                          'student42: A',
                          'student43: B',
                          'student44: C',
                          'student45: B',
                          'student46: B',
                          'student47: C',
                          'student48: B',
                          'student49: B',
                          'student50: B',
                          'student51: B',
                          'student52: C',
                          'student53: B',
                          'student54: C',
                          'student55: A',
                          'student56: A',
                          'student57: B',
                          'student58: C',
                          'student59: B',
                          'student60: B',
                          'student61: B',
                          'student62: B',
                          'student63: B',
                          'student64: B',
                          'student65: C',
                          'student66: C',
                          'student67: C',
                          'student68: B',
                          'student69: B',
                          'student70: B',
                          'student71: B',
                          'student72: C',
                          'student73: B',
                          'student74: B',
                          'student75: B',
                          'student76: B',
                          'student77: B',
                          'student78: C',
                          'student79: B',
                          'student80: B',
                          'student81: B',
                          'student82: C',
                          'student83: B',
                          'student84: C',
                          'student85: C',
                          'student86: B',
                          'student87: A',
                          'student88: B',
                          'student89: C',
                          'student90: B',
                          'student91: B',
                          'student92: C',
                          'student93: C',
                          'student94: C',
                          'student95: A',
                          'student96: B',
                          'student97: A',
                          'student98: B',
                          'student99: C',
                          'student100: B']

In [27]:
def ex3(filename):
    # Complete this function to read grades from `filename` and find the minimum
    # student test averages. File has student_name, test1_score, test2_score,
    # test3_score, test4_score, test5_score. This function must use a lambda
    # function and use the min() function to find the student with the minimum
    # test average. The input to the min function should be
    # a list of lines. Ex. ['student1,33,34,35,36,45', 'student2,33,34,35,36,75']
    # input filename
    # output: (lambda_func, line_with_min_student) -- example (lambda_func, 'student1,33,34,35,36,45')

    # BEGIN SOLUTION
    # open filename as
    # with open(filename) as f: 
    #     readline=f.read().
    # input_data=[]
    # for lines in range(0,len(readline),2):
    #     input_data.append(readline[lines])


    input_data=[]
    with open(filename) as file: 
        for line in file:
            # print(line.strip())
            line=line.strip()
        #     if line!=" ":
        #         input_data.append(line)
        # print(input_data)
            # inp=[input_data.append(line) if line!='' for elem in lst]
            if line=='':
                continue
            input_data.append(line)
        print(input_data)
    #     input_data.append(readline[lines])
    # print(input_data)
    # l_func = lambda x: sum(list(map(int, x.split(",")[1:]))) / 5
    # list_res=[l_func(c) for c in input_data]
    # print()


    # inp=[elem*3 if elem%2==0 else elem*5 for elem in lst]
    # l_func = lambda x: sum(list(map(int, x.split(",")[1:]))) / len(x.split(",")[1:])
    # new_list = min(input_data, key=l_func)
    # return (l_func, new_list)

ex3('ex3_data.txt')

['student1,94,88,86,78,94', '', 'student2,88,78,80,84,80', '', 'student3,84,97,85,73,76', '', 'student4,72,99,72,86,82', '', 'student5,71,92,71,77,91', '', 'student6,89,96,77,71,76', '', 'student7,97,74,65,71,87', '', 'student8,90,69,67,76,70', '', 'student9,81,83,100,87,92', '', 'student10,87,72,70,89,69', '', 'student11,72,69,69,65,91', '', 'student12,78,84,76,76,83', '', 'student13,86,66,70,84,97', '', 'student14,85,84,97,87,88', '', 'student15,67,82,82,76,81', '', 'student16,98,73,72,85,77', '', 'student17,74,79,87,87,94', '', 'student18,69,95,94,72,94', '', 'student19,76,79,69,86,72', '', 'student20,95,78,81,80,85', '', 'student21,91,87,96,82,74', '', 'student22,66,89,67,84,84', '', 'student23,69,100,72,96,85', '', 'student24,66,83,87,81,85', '', 'student25,95,98,97,94,75', '', 'student26,78,93,71,67,94', '', 'student27,80,86,70,80,78', '', 'student28,89,89,94,73,66', '', 'student29,90,85,75,79,72', '', 'student30,65,98,94,85,67', '', 'student31,79,69,88,95,74', '', 'student32,78,87,79,72,66', '', 'student33,67,65,99,91,97', '', 'student34,93,84,97,99,73', '', 'student35,76,74,84,93,76', '', 'student36,67,81,85,65,93', '', 'student37,97,80,100,80,65', '', 'student38,84,90,66,81,94', '', 'student39,78,80,71,74,79', '', 'student40,81,71,73,80,89', '', 'student41,86,98,77,94,67', '', 'student42,84,99,93,90,87', '', 'student43,97,78,75,66,94', '', 'student44,68,82,87,91,69', '', 'student45,83,74,99,76,95', '', 'student46,96,83,79,89,71', '', 'student47,70,85,94,73,74', '', 'student48,99,72,92,65,87', '', 'student49,78,93,99,77,85', '', 'student50,96,91,76,72,66', '', 'student51,94,86,77,91,96', '', 'student52,79,68,81,100,67', '', 'student53,97,73,91,80,78', '', 'student54,88,77,74,65,91', '', 'student55,94,99,85,83,99', '', 'student56,89,99,97,85,98', '', 'student57,90,85,90,90,76', '', 'student58,78,69,67,87,69', '', 'student59,79,81,98,79,97', '', 'student60,98,77,83,78,80', '', 'student61,90,69,76,98,67', '', 'student62,71,95,90,86,72', '', 'student63,88,86,88,65,88', '', 'student64,86,86,94,89,71', '', 'student65,66,84,87,66,75', '', 'student66,71,81,73,67,92', '', 'student67,99,67,72,80,75', '', 'student68,87,67,80,89,79', '', 'student69,86,78,98,83,94', '', 'student70,99,71,97,80,83', '', 'student71,84,89,90,99,85', '', 'student72,94,75,80,69,78', '', 'student73,82,86,68,95,86', '', 'student74,76,99,78,83,87', '', 'student75,71,93,77,90,91', '', 'student76,92,73,77,86,84', '', 'student77,84,93,69,95,86', '', 'student78,80,82,78,65,80', '', 'student79,88,71,72,99,100', '', 'student80,88,72,95,65,82', '', 'student81,90,89,88,82,95', '', 'student82,74,80,92,81,69', '', 'student83,77,95,96,96,72', '', 'student84,77,68,95,87,69', '', 'student85,92,68,65,67,78', '', 'student86,91,75,77,97,95', '', 'student87,92,71,98,96,96', '', 'student88,88,83,70,100,73', '', 'student89,79,90,65,82,80', '', 'student90,91,77,93,75,89', '', 'student91,83,74,81,99,70', '', 'student92,79,77,70,79,75', '', 'student93,66,67,88,97,71', '', 'student94,76,92,67,84,75', '', 'student95,91,81,92,85,99', '', 'student96,98,100,74,86,86', '', 'student97,97,89,89,99,100', '', 'student98,74,84,95,100,77', '', 'student99,76,78,67,99,71', '', 'student100,86,83,79,96,76', '']

In [6]:
def ex4(data):
    # Complete this function to read grades from `filename` and map the test average to letter
    # grades using map and lambda. File has student_name, test1_score, test2_score,
    # test3_score, test4_score, test5_score. This function must use a lambda
    # function and map() function.
    # The input to the map function should be
    # a list of lines. Ex. ['student1,73,74,75,76,75', ...]. Output is a list of strings in the format
    # studentname: Letter Grade -- 'student1: C'
    # input filename
    # output: (lambda_func, list_of_studentname_and_lettergrade) -- example (lambda_func, ['student1: C', ...])

    # Use this average to do the grade mapping. Round the average grade.
    # D = 65<=average<70
    # C = 70<=average<80
    # B = 80<=average<90
    # A = 90<=average
    # Define a function that takes in a number grade and returns the letter grade and use
    # it inside the lambda function. 
    ## HINT: create a function 

    # BEGIN SOLUTION
    with open(data) as f: 
        readline=f.read().split("\n")
    # print(readline)
    input_data=[]
    for lines in range(0,len(readline),2):
        input_data.append(readline[lines])
    def letter_grade(score): 
    # BEGIN SOLUTION
        if score >=90:
            return 'A'
        elif score >=80:
            return 'B'
        elif score >=70:
            return 'C'
        elif score >=60:
            return 'D'
        else:
            return 'F'
    # l_func = lambda x: sum(list(map(int, x.split(",")[1:]))) / 5
    # list_res=[letter_grade(round(l_func(c))) for c in input_data]
    # student_fun=lambda row: row.split(',')[0]
    # student_lst=[student_fun(p) for p in input_data]
    # final_res=[f'{student_lst[each]}: {list_res[each]}' for each in range(len(list_res))]
    lambda_function=lambda line:f"{line.split(',')[0]}: {letter_grade(round(sum(map(int, line.split(',')[1:]))/5))}"
    # return (lambda_function,input_data,key=lambda_function))
    lambda_function(input_data)

    return final_res
    
ex4('ex3_data.txt')

AttributeError: 'list' object has no attribute 'split'

In [8]:
def ex9(title, header, data, sort_header_name, filename):
    # This problem is EASY!!!!!
    # Open up ex9_*_solution.txt and look at the output based on the input parameters, which
    # can be found in the test_assignment5.py file
    # Function inputs: 
    # title -- title of the table -- a string
    # header -- header of the table  -- a tuple
    # data -- rows of data, which is a tuple of tuples
    # sort_header_name -- name of the header to sort the data by
    # filename -- name of file to write the table to
    # Your job is to create the table in the file and write it to `filename`
    # Note that you need to dynamically figure out the width of each column based on 
    # maximum possible length based on the header and data. This is what makes this problem hard. 
    # Once you have determined the maximum length of each column, make sure to pad it with 1 space
    # to the right and left. Center align all the values. 
    # OUTPUT: you are writing the table to a file
    # ******NOTE: USE sort_header_name to sort the data using sorted and lambda. Sorting might be incorrect, 
    # but that is fine. We will explore this issue in class. I just want you have the code in place. 
    # NOTE: sort in descending order

    ### BEGIN SOLUTION
    table_data=header
    heading_length=[]
    for i in range(len(table_data)):
        heading_length.append(len(str(table_data[i])))
    heading_length

    record_length=[0]*len(table_data)
    for i in data:
        for j in range(len(i)):
            # print(i[j])
            record_length[j]=max(record_length[j],len(str(i[j])))

    final_len=[]
    final_list=list(zip(heading_length,record_length))
    for i in final_list:
        # print(max(i))
        final_len.append(max(i)+2)
    final_len
    # print(sum(final_len)+ (len(final_len)*2))
    # print(final_len)
    total_len=6+len(data)
    # print(total_len)

    row_outline=''
    for b in final_len:
        row_outline+='+'+('-'*b)
    row_outline+='+'

    rows_cumi=[]
    for t in data:
        rows=''
        for cell in range(len(t)):
            rows+='|'+ f'{t[cell]:^{final_len[cell]}}'
        rows_cumi.append(rows+'|')
    rows_cumi

    title = '|' + f'{title:^{len(row_outline)-2}}' + '|'
    top_border= '-'*len(row_outline)
    header=""
    for headings in range(len(table_data)):
            header+='|'+ f'{table_data[headings]:^{final_len[headings]}}'
    header=header + "|"

    # top_border
    # title
    # row_outline
    # header
    # row_outline
    final_row_list=[top_border,title,row_outline,header,row_outline]

    for row_data in rows_cumi:
        final_row_list.append(row_data)

    final_row_list.append(row_outline)

    final_file = '\n'.join(final_row_list)
    my_file = open(filename, 'w')
    my_file.write(final_file)
    my_file.close()
    # print(final_file)
    ### END SOLUTION

In [9]:
title = 'Cereal Yields (kg/ha)'
header = ('Country', '1980', '1990', '2000', '2010')
data = (('China', 2937, 4321, 4752, 5527),('Germany', 4225, 5411, 6453, 6718),('United States', 3772, 4755, 5854, 6988),)

In [10]:
ex9(title, header, data, '2000', 'ex9_1.txt')

In [67]:
data = (
            ('China', 2937, 4321, 4752, 5527),
            ('Germany', 4225, 5411, 6453, 6718),
            ('United States', 3772, 4755, 5854, 6988),
        )
data=[list(x) for x in list(data)]
# print(data)
temp=[x[3] for x in data]
temp1=[]
for i in range(len(temp)):
    temp[i]=(temp[i],i)
temp.sort(reverse=True)
# temp_sort=sorted((temp,reverse=True))
sorte=[]
for j in temp_sort:
    sorte.append(j[1])
sorte
new_data=[]
for line_data in sorte:
    print(data[line_data])
#     new_data.append(data[line_data])
# new_data

['China', 2937, 4321, 4752, 5527]
['United States', 3772, 4755, 5854, 6988]
['Germany', 4225, 5411, 6453, 6718]

In [66]:
data = (
            ('China', 2937, 4321, 4752, 5527),
            ('Germany', 4225, 5411, 6453, 6718),
            ('United States', 3772, 4755, 5854, 6988),
        )
data[1]

('Germany', 4225, 5411, 6453, 6718)

In [19]:
sortby='2000'
header = ('Country', '1980', '1990', '2000', '2010')
mydict={}


for va in range(len(header)):
    mydict[header[va]]=data[va]

    
heasder_list=list(header)
for pos in range(len(heasder_list)):
    if sortby==header[pos]:
        print(pos)
# new_data=[]

# lambda_function=lambda row:int(row["test3"])
# return (lambda_function,sorted(grades,key=lambda_function))
# for r in data:
#     new_data.append(r)
# print(new_data)